import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.ext.asyncio import AsyncAttrs
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention so Alembic autogenerate produces the same
# constraint/index names on every machine and every run — without this,
# SQLAlchemy lets the database pick default names, which differ across
# dialects and make autogenerated migrations noisy/non-reproducible.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(AsyncAttrs, DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    # Without this, a column with a server-computed value (created_at's
    # server_default, updated_at's onupdate=func.now()) is left "expired"
    # after flush/commit. A later *synchronous* attribute read (e.g.
    # pydantic's model_validate) then tries to lazily re-fetch it outside
    # any async context and raises MissingGreenlet. eager_defaults=True
    # fetches those values via RETURNING as part of the flush itself, so
    # they're already populated in memory by the time anything reads them.
    __mapper_args__ = {"eager_defaults": True}


class UUIDPrimaryKeyMixin:
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
